### ISSUE TITLE
最后两个简单粗暴的问题

### ISSUE THREAD

**Issue by damumu0809** [nodejh/scunet.cn#2]
1.插入成功但是变量还是没有写进表里面
2.点击获取验证码之后button内容一直在变

**Comment by nodejh** [comment]
倒计时的代码如下：

```
setInterval(function(){
    if(count == 0){
        $('#send_sms').removeClass("sms_active");
        $('#send_sms').val("获取验证码");
    } else{
        $('#send_sms').val(count +"s后重新获取");
        count--;
    }
 }, 1000);

```

你可以在 if(count == 0) 上面打印出来，就会发现，只要第一次 count 减少到0之后，setInterval 中 的 count 永远为0.

而 var count = 60，则定义出来的是一个新的 count 变量。 setInterval 中的count还是最初的count。
